# =============================================================================
# fix-icons.ps1
# Mass replace broken icon libraries (MDI, Boxicons) with Bootstrap Icons
# across all EJS view files in the billing-kalimasada project.
# =============================================================================

$root = Split-Path -Parent $PSScriptRoot
$viewsPath = Join-Path $root "views"

Write-Host "=== Icon Fix Script ===" -ForegroundColor Cyan
Write-Host "Target: $viewsPath" -ForegroundColor Yellow

# Kumpulkan semua file .ejs
$ejsFiles = Get-ChildItem -Path $viewsPath -Recurse -Filter "*.ejs"
Write-Host "Found $($ejsFiles.Count) EJS files" -ForegroundColor Yellow

# =============================================================================
# MAPPING: icon lama -> Bootstrap Icons pengganti
# Format: @("pattern_regex", "replacement_string")
# =============================================================================
$iconMappings = @(
    # ------ MDI Icons (Material Design Icons) ------
    # Summary/stat cards icons
    @('mdi mdi-account-group[^"]*', 'bi bi-people-fill'),
    @('mdi mdi-account-check[^"]*', 'bi bi-person-check-fill'),
    @('mdi mdi-account-multiple[^"]*', 'bi bi-people'),
    @('mdi mdi-account-off[^"]*', 'bi bi-person-x-fill'),
    @('mdi mdi-account-plus[^"]*', 'bi bi-person-plus-fill'),
    @('mdi mdi-account-minus[^"]*', 'bi bi-person-dash-fill'),
    @('mdi mdi-account[^"]*', 'bi bi-person-fill'),
    @('mdi mdi-cash-check[^"]*', 'bi bi-check-circle-fill'),
    @('mdi mdi-cash-remove[^"]*', 'bi bi-clock-history'),
    @('mdi mdi-cash-multiple[^"]*', 'bi bi-currency-exchange'),
    @('mdi mdi-cash-refund[^"]*', 'bi bi-arrow-counterclockwise'),
    @('mdi mdi-cash[^"]*', 'bi bi-cash-coin'),
    @('mdi mdi-alert-circle[^"]*', 'bi bi-slash-circle-fill'),
    @('mdi mdi-alert-octagon[^"]*', 'bi bi-exclamation-octagon-fill'),
    @('mdi mdi-alert[^"]*', 'bi bi-exclamation-triangle-fill'),
    @('mdi mdi-receipt-outline[^"]*', 'bi bi-receipt'),
    @('mdi mdi-receipt[^"]*', 'bi bi-receipt-cutoff'),
    @('mdi mdi-chart-line[^"]*', 'bi bi-graph-up-arrow'),
    @('mdi mdi-chart-bar[^"]*', 'bi bi-bar-chart-fill'),
    @('mdi mdi-chart-pie[^"]*', 'bi bi-pie-chart-fill'),
    @('mdi mdi-chart-donut[^"]*', 'bi bi-pie-chart'),
    @('mdi mdi-chart[^"]*', 'bi bi-graph-up'),
    @('mdi mdi-wifi-off[^"]*', 'bi bi-wifi-off'),
    @('mdi mdi-wifi[^"]*', 'bi bi-wifi'),
    @('mdi mdi-router-wireless[^"]*', 'bi bi-router-fill'),
    @('mdi mdi-router[^"]*', 'bi bi-router'),
    @('mdi mdi-server[^"]*', 'bi bi-server'),
    @('mdi mdi-network[^"]*', 'bi bi-hdd-network-fill'),
    @('mdi mdi-check-circle[^"]*', 'bi bi-check-circle-fill'),
    @('mdi mdi-check[^"]*', 'bi bi-check-lg'),
    @('mdi mdi-close-circle[^"]*', 'bi bi-x-circle-fill'),
    @('mdi mdi-close[^"]*', 'bi bi-x-lg'),
    @('mdi mdi-delete[^"]*', 'bi bi-trash3-fill'),
    @('mdi mdi-pencil[^"]*', 'bi bi-pencil-fill'),
    @('mdi mdi-eye-off[^"]*', 'bi bi-eye-slash-fill'),
    @('mdi mdi-eye[^"]*', 'bi bi-eye-fill'),
    @('mdi mdi-refresh[^"]*', 'bi bi-arrow-clockwise'),
    @('mdi mdi-plus-circle[^"]*', 'bi bi-plus-circle-fill'),
    @('mdi mdi-plus[^"]*', 'bi bi-plus-lg'),
    @('mdi mdi-minus[^"]*', 'bi bi-dash-lg'),
    @('mdi mdi-magnify[^"]*', 'bi bi-search'),
    @('mdi mdi-filter[^"]*', 'bi bi-funnel-fill'),
    @('mdi mdi-download[^"]*', 'bi bi-download'),
    @('mdi mdi-upload[^"]*', 'bi bi-upload'),
    @('mdi mdi-export[^"]*', 'bi bi-box-arrow-up-right'),
    @('mdi mdi-import[^"]*', 'bi bi-box-arrow-in-down'),
    @('mdi mdi-lock[^"]*', 'bi bi-lock-fill'),
    @('mdi mdi-lock-open[^"]*', 'bi bi-unlock-fill'),
    @('mdi mdi-key[^"]*', 'bi bi-key-fill'),
    @('mdi mdi-settings[^"]*', 'bi bi-gear-fill'),
    @('mdi mdi-cog[^"]*', 'bi bi-gear-fill'),
    @('mdi mdi-home[^"]*', 'bi bi-house-fill'),
    @('mdi mdi-map-marker[^"]*', 'bi bi-geo-alt-fill'),
    @('mdi mdi-map[^"]*', 'bi bi-map-fill'),
    @('mdi mdi-phone[^"]*', 'bi bi-telephone-fill'),
    @('mdi mdi-email[^"]*', 'bi bi-envelope-fill'),
    @('mdi mdi-whatsapp[^"]*', 'bi bi-whatsapp'),
    @('mdi mdi-message-text[^"]*', 'bi bi-chat-text-fill'),
    @('mdi mdi-message[^"]*', 'bi bi-chat-fill'),
    @('mdi mdi-bell[^"]*', 'bi bi-bell-fill'),
    @('mdi mdi-calendar[^"]*', 'bi bi-calendar3'),
    @('mdi mdi-clock[^"]*', 'bi bi-clock-fill'),
    @('mdi mdi-timer[^"]*', 'bi bi-stopwatch-fill'),
    @('mdi mdi-file-document[^"]*', 'bi bi-file-earmark-text-fill'),
    @('mdi mdi-file-pdf[^"]*', 'bi bi-file-earmark-pdf-fill'),
    @('mdi mdi-file-excel[^"]*', 'bi bi-file-earmark-spreadsheet-fill'),
    @('mdi mdi-file[^"]*', 'bi bi-file-earmark-fill'),
    @('mdi mdi-folder[^"]*', 'bi bi-folder-fill'),
    @('mdi mdi-package[^"]*', 'bi bi-box-seam-fill'),
    @('mdi mdi-tag[^"]*', 'bi bi-tag-fill'),
    @('mdi mdi-label[^"]*', 'bi bi-tag'),
    @('mdi mdi-information[^"]*', 'bi bi-info-circle-fill'),
    @('mdi mdi-help-circle[^"]*', 'bi bi-question-circle-fill'),
    @('mdi mdi-dots-vertical[^"]*', 'bi bi-three-dots-vertical'),
    @('mdi mdi-dots-horizontal[^"]*', 'bi bi-three-dots'),
    @('mdi mdi-menu[^"]*', 'bi bi-list'),
    @('mdi mdi-arrow-left[^"]*', 'bi bi-arrow-left'),
    @('mdi mdi-arrow-right[^"]*', 'bi bi-arrow-right'),
    @('mdi mdi-arrow-up[^"]*', 'bi bi-arrow-up'),
    @('mdi mdi-arrow-down[^"]*', 'bi bi-arrow-down'),
    @('mdi mdi-swap-horizontal[^"]*', 'bi bi-arrow-left-right'),
    @('mdi mdi-transfer[^"]*', 'bi bi-arrow-left-right'),
    @('mdi mdi-history[^"]*', 'bi bi-clock-history'),
    @('mdi mdi-shield[^"]*', 'bi bi-shield-fill'),
    @('mdi mdi-percent[^"]*', 'bi bi-percent'),
    @('mdi mdi-currency-usd[^"]*', 'bi bi-currency-dollar'),
    @('mdi mdi-trending-up[^"]*', 'bi bi-graph-up-arrow'),
    @('mdi mdi-trending-down[^"]*', 'bi bi-graph-down-arrow'),
    @('mdi mdi-bank[^"]*', 'bi bi-bank2'),
    @('mdi mdi-credit-card[^"]*', 'bi bi-credit-card-fill'),
    @('mdi mdi-printer[^"]*', 'bi bi-printer-fill'),
    @('mdi mdi-share[^"]*', 'bi bi-share-fill'),
    @('mdi mdi-link[^"]*', 'bi bi-link-45deg'),
    @('mdi mdi-logout[^"]*', 'bi bi-box-arrow-right'),
    @('mdi mdi-login[^"]*', 'bi bi-box-arrow-in-right'),
    @('mdi mdi-power[^"]*', 'bi bi-power'),
    @('mdi mdi-pause[^"]*', 'bi bi-pause-fill'),
    @('mdi mdi-play[^"]*', 'bi bi-play-fill'),
    @('mdi mdi-stop[^"]*', 'bi bi-stop-fill'),
    @('mdi mdi-repeat[^"]*', 'bi bi-arrow-repeat'),
    @('mdi mdi-flash[^"]*', 'bi bi-lightning-fill'),
    @('mdi mdi-lightning-bolt[^"]*', 'bi bi-lightning-fill'),
    @('mdi mdi-access-point[^"]*', 'bi bi-broadcast'),
    @('mdi mdi-ethernet[^"]*', 'bi bi-ethernet'),
    @('mdi mdi-ip-network[^"]*', 'bi bi-hdd-network'),
    @('mdi mdi-cable-data[^"]*', 'bi bi-usb-symbol'),
    @('mdi mdi-sort[^"]*', 'bi bi-sort-down'),
    @('mdi mdi-table[^"]*', 'bi bi-table'),
    @('mdi mdi-database[^"]*', 'bi bi-database-fill'),
    @('mdi mdi-sync[^"]*', 'bi bi-arrow-repeat'),
    @('mdi mdi-wrench[^"]*', 'bi bi-wrench-adjustable'),
    @('mdi mdi-tools[^"]*', 'bi bi-tools'),
    @('mdi mdi-lifebuoy[^"]*', 'bi bi-life-preserver'),
    @('mdi mdi-headset[^"]*', 'bi bi-headset'),
    @('mdi mdi-earth[^"]*', 'bi bi-globe2'),
    @('mdi mdi-clipboard-list[^"]*', 'bi bi-clipboard-check-fill'),
    @('mdi mdi-clipboard[^"]*', 'bi bi-clipboard-fill'),
    @('mdi mdi-note-text[^"]*', 'bi bi-sticky-fill'),
    @('mdi mdi-note[^"]*', 'bi bi-sticky'),
    @('mdi mdi-image[^"]*', 'bi bi-image-fill'),
    @('mdi mdi-map-marker-off[^"]*', 'bi bi-geo-alt'),
    @('mdi mdi-speedometer[^"]*', 'bi bi-speedometer'),
    @('mdi mdi-gauge[^"]*', 'bi bi-speedometer2'),
    @('mdi mdi-pulse[^"]*', 'bi bi-activity'),
    @('mdi mdi-radio-tower[^"]*', 'bi bi-broadcast-pin'),
    @('mdi mdi-antenna[^"]*', 'bi bi-broadcast'),
    # fallback untuk mdi yang tidak dikenal
    @('mdi mdi-[a-z0-9\-]+', 'bi bi-circle-fill'),

    # ------ BOXICONS (bx bx-*, bx bxs-*, bx bxl-*) ------
    # Navigation & UI
    @('bx bx-menu-alt-left', 'bi bi-layout-sidebar'),
    @('bx bx-menu-alt-right', 'bi bi-layout-sidebar-reverse'),
    @('bx bx-menu', 'bi bi-list'),
    @('bx bx-x', 'bi bi-x-lg'),
    @('bx bx-search-alt', 'bi bi-search'),
    @('bx bx-search', 'bi bi-search'),
    @('bx bx-filter-alt', 'bi bi-funnel-fill'),
    @('bx bx-filter', 'bi bi-funnel'),
    @('bx bx-sort-alt-2', 'bi bi-sort-down-alt'),
    @('bx bx-sort', 'bi bi-sort-down'),
    @('bx bx-refresh', 'bi bi-arrow-clockwise'),
    @('bx bx-sync', 'bi bi-arrow-repeat'),
    @('bx bx-reset', 'bi bi-arrow-counterclockwise'),
    @('bx bx-undo', 'bi bi-arrow-counterclockwise'),
    # User & People
    @('bx bx-user-check', 'bi bi-person-check-fill'),
    @('bx bx-user-plus', 'bi bi-person-plus-fill'),
    @('bx bx-user-minus', 'bi bi-person-dash-fill'),
    @('bx bx-user-x', 'bi bi-person-x-fill'),
    @('bx bx-user-circle', 'bi bi-person-circle'),
    @('bx bx-user-voice', 'bi bi-person-lines-fill'),
    @('bx bx-user-pin', 'bi bi-person-badge-fill'),
    @('bx bx-user', 'bi bi-person-fill'),
    @('bx bx-group', 'bi bi-people-fill'),
    # CRUD Actions
    @('bx bx-plus-circle', 'bi bi-plus-circle-fill'),
    @('bx bx-plus', 'bi bi-plus-lg'),
    @('bx bx-minus-circle', 'bi bi-dash-circle-fill'),
    @('bx bx-minus', 'bi bi-dash-lg'),
    @('bx bx-edit-alt', 'bi bi-pencil-square'),
    @('bx bx-edit', 'bi bi-pencil-fill'),
    @('bx bx-pencil', 'bi bi-pencil'),
    @('bx bx-trash-alt', 'bi bi-trash3'),
    @('bx bx-trash', 'bi bi-trash3-fill'),
    @('bx bx-show-alt', 'bi bi-eye'),
    @('bx bx-show', 'bi bi-eye-fill'),
    @('bx bx-hide', 'bi bi-eye-slash-fill'),
    @('bx bx-save', 'bi bi-floppy-fill'),
    @('bx bx-copy-alt', 'bi bi-copy'),
    @('bx bx-copy', 'bi bi-files'),
    @('bx bx-duplicate', 'bi bi-layers'),
    @('bx bx-check-circle', 'bi bi-check-circle-fill'),
    @('bx bx-check-square', 'bi bi-check-square-fill'),
    @('bx bx-check', 'bi bi-check-lg'),
    @('bx bx-error-circle', 'bi bi-exclamation-circle-fill'),
    @('bx bx-error-alt', 'bi bi-exclamation-triangle-fill'),
    @('bx bx-error', 'bi bi-exclamation-octagon-fill'),
    @('bx bx-block', 'bi bi-slash-circle-fill'),
    @('bx bx-lock-alt', 'bi bi-lock-fill'),
    @('bx bx-lock-open-alt', 'bi bi-unlock-fill'),
    @('bx bx-lock-open', 'bi bi-unlock'),
    @('bx bx-lock', 'bi bi-lock'),
    # File & Data
    @('bx bx-file-blank', 'bi bi-file-earmark'),
    @('bx bx-file-find', 'bi bi-file-earmark-search'),
    @('bx bx-file', 'bi bi-file-earmark-fill'),
    @('bx bx-folder-open', 'bi bi-folder2-open'),
    @('bx bx-folder', 'bi bi-folder-fill'),
    @('bx bx-cloud-download', 'bi bi-cloud-download-fill'),
    @('bx bx-cloud-upload', 'bi bi-cloud-upload-fill'),
    @('bx bx-cloud', 'bi bi-cloud-fill'),
    @('bx bx-download', 'bi bi-download'),
    @('bx bx-upload', 'bi bi-upload'),
    @('bx bx-import', 'bi bi-box-arrow-in-down'),
    @('bx bx-export', 'bi bi-box-arrow-up-right'),
    @('bx bx-spreadsheet', 'bi bi-file-earmark-spreadsheet-fill'),
    @('bx bx-data', 'bi bi-database-fill'),
    @('bx bx-server', 'bi bi-server'),
    @('bx bx-archive-in', 'bi bi-archive'),
    @('bx bx-archive', 'bi bi-archive-fill'),
    # Charts & Stats
    @('bx bx-bar-chart-alt-2', 'bi bi-bar-chart-fill'),
    @('bx bx-bar-chart-alt', 'bi bi-bar-chart'),
    @('bx bx-bar-chart', 'bi bi-bar-chart-steps'),
    @('bx bx-line-chart', 'bi bi-graph-up'),
    @('bx bx-pie-chart-alt-2', 'bi bi-pie-chart-fill'),
    @('bx bx-pie-chart-alt', 'bi bi-pie-chart'),
    @('bx bx-pie-chart', 'bi bi-pie-chart'),
    @('bx bx-trending-up', 'bi bi-graph-up-arrow'),
    @('bx bx-trending-down', 'bi bi-graph-down-arrow'),
    @('bx bx-stats', 'bi bi-bar-chart-line-fill'),
    @('bx bx-analyse', 'bi bi-graph-up'),
    @('bx bx-chart', 'bi bi-graph-up'),
    @('bx bx-tachometer', 'bi bi-speedometer2'),
    @('bx bx-pulse', 'bi bi-activity'),
    # Money & Finance
    @('bx bx-money-withdraw', 'bi bi-cash-coin'),
    @('bx bx-money', 'bi bi-cash-stack'),
    @('bx bx-credit-card-alt', 'bi bi-credit-card-2-front-fill'),
    @('bx bx-credit-card', 'bi bi-credit-card-fill'),
    @('bx bx-dollar-circle', 'bi bi-currency-dollar'),
    @('bx bx-dollar', 'bi bi-cash'),
    @('bx bx-receipt', 'bi bi-receipt'),
    @('bx bx-purchase-tag-alt', 'bi bi-tag'),
    @('bx bx-purchase-tag', 'bi bi-tag-fill'),
    @('bx bx-coin-stack', 'bi bi-stack'),
    @('bx bx-coin', 'bi bi-coin'),
    # Navigation
    @('bx bx-home-alt', 'bi bi-house-fill'),
    @('bx bx-home', 'bi bi-house'),
    @('bx bx-map-pin', 'bi bi-geo-alt-fill'),
    @('bx bx-map-alt', 'bi bi-map-fill'),
    @('bx bx-map', 'bi bi-map'),
    @('bx bx-navigation', 'bi bi-compass-fill'),
    @('bx bx-current-location', 'bi bi-crosshair'),
    @('bx bx-directions', 'bi bi-signpost-fill'),
    @('bx bx-globe-alt', 'bi bi-globe2'),
    @('bx bx-globe', 'bi bi-globe'),
    @('bx bx-world', 'bi bi-globe-americas'),
    @('bx bx-left-arrow-alt', 'bi bi-arrow-left'),
    @('bx bx-right-arrow-alt', 'bi bi-arrow-right'),
    @('bx bx-up-arrow-alt', 'bi bi-arrow-up'),
    @('bx bx-down-arrow-alt', 'bi bi-arrow-down'),
    @('bx bx-chevron-left', 'bi bi-chevron-left'),
    @('bx bx-chevron-right', 'bi bi-chevron-right'),
    @('bx bx-chevron-up', 'bi bi-chevron-up'),
    @('bx bx-chevron-down', 'bi bi-chevron-down'),
    @('bx bx-first-page', 'bi bi-skip-start-fill'),
    @('bx bx-last-page', 'bi bi-skip-end-fill'),
    # Communication
    @('bx bx-phone-call', 'bi bi-telephone-forward-fill'),
    @('bx bx-phone', 'bi bi-telephone-fill'),
    @('bx bx-message-alt-detail', 'bi bi-chat-dots-fill'),
    @('bx bx-message-alt', 'bi bi-chat-fill'),
    @('bx bx-message-detail', 'bi bi-chat-text-fill'),
    @('bx bx-message', 'bi bi-chat'),
    @('bx bx-envelope-open', 'bi bi-envelope-open-fill'),
    @('bx bx-envelope', 'bi bi-envelope-fill'),
    @('bx bx-send', 'bi bi-send-fill'),
    @('bx bx-mail-send', 'bi bi-mailbox2'),
    @('bx bx-bell', 'bi bi-bell-fill'),
    @('bx bx-notification', 'bi bi-app-indicator'),
    # Settings & Config
    @('bx bx-cog', 'bi bi-gear-fill'),
    @('bx bx-wrench', 'bi bi-wrench-adjustable'),
    @('bx bx-customize', 'bi bi-palette-fill'),
    @('bx bx-slider', 'bi bi-sliders'),
    @('bx bx-equalizer', 'bi bi-sliders2'),
    @('bx bx-adjust', 'bi bi-toggles'),
    @('bx bx-toggle-right', 'bi bi-toggle-on'),
    @('bx bx-toggle-left', 'bi bi-toggle-off'),
    # Time & Calendar
    @('bx bx-calendar-event', 'bi bi-calendar-event-fill'),
    @('bx bx-calendar-check', 'bi bi-calendar-check-fill'),
    @('bx bx-calendar-x', 'bi bi-calendar-x-fill'),
    @('bx bx-calendar-alt', 'bi bi-calendar3-range'),
    @('bx bx-calendar', 'bi bi-calendar3'),
    @('bx bx-time-five', 'bi bi-clock-fill'),
    @('bx bx-timer', 'bi bi-stopwatch-fill'),
    @('bx bx-stopwatch', 'bi bi-stopwatch'),
    @('bx bx-history', 'bi bi-clock-history'),
    # Status & Alerts
    @('bx bx-info-circle', 'bi bi-info-circle-fill'),
    @('bx bx-help-circle', 'bi bi-question-circle-fill'),
    @('bx bx-shield-alt-2', 'bi bi-shield-lock-fill'),
    @('bx bx-shield-alt', 'bi bi-shield-fill-check'),
    @('bx bx-shield-x', 'bi bi-shield-x'),
    @('bx bx-shield', 'bi bi-shield-fill'),
    @('bx bx-flag', 'bi bi-flag-fill'),
    @('bx bx-bookmark-alt', 'bi bi-bookmark-star-fill'),
    @('bx bx-bookmark', 'bi bi-bookmark-fill'),
    @('bx bx-star', 'bi bi-star-fill'),
    @('bx bx-badge-check', 'bi bi-patch-check-fill'),
    @('bx bx-badge', 'bi bi-patch-fill'),
    @('bx bx-medal', 'bi bi-award-fill'),
    @('bx bx-award', 'bi bi-trophy-fill'),
    # Network & Tech
    @('bx bx-wifi-off', 'bi bi-wifi-off'),
    @('bx bx-wifi', 'bi bi-wifi'),
    @('bx bx-broadcast', 'bi bi-broadcast'),
    @('bx bx-radio', 'bi bi-broadcast-pin'),
    @('bx bx-network-chart', 'bi bi-diagram-3-fill'),
    @('bx bx-devices', 'bi bi-devices'),
    @('bx bx-desktop', 'bi bi-pc-display-horizontal'),
    @('bx bx-mobile-alt', 'bi bi-phone-fill'),
    @('bx bx-mobile', 'bi bi-phone'),
    @('bx bx-laptop', 'bi bi-laptop'),
    @('bx bx-chip', 'bi bi-cpu-fill'),
    @('bx bx-cable-car', 'bi bi-ethernet'),
    @('bx bx-plug', 'bi bi-plug-fill'),
    # Print & Doc
    @('bx bx-printer', 'bi bi-printer-fill'),
    @('bx bx-share-alt', 'bi bi-share-fill'),
    @('bx bx-share', 'bi bi-box-arrow-up'),
    @('bx bx-link-alt', 'bi bi-link-45deg'),
    @('bx bx-link-external', 'bi bi-box-arrow-up-right'),
    @('bx bx-link', 'bi bi-link'),
    @('bx bx-qr-scan', 'bi bi-qr-code-scan'),
    @('bx bx-qr', 'bi bi-qr-code'),
    @('bx bx-barcode-reader', 'bi bi-upc-scan'),
    @('bx bx-barcode', 'bi bi-upc'),
    # Misc content
    @('bx bx-log-out-circle', 'bi bi-box-arrow-right'),
    @('bx bx-log-out', 'bi bi-box-arrow-right'),
    @('bx bx-log-in-circle', 'bi bi-box-arrow-in-right'),
    @('bx bx-log-in', 'bi bi-box-arrow-in-right'),
    @('bx bx-power-off', 'bi bi-power'),
    @('bx bx-cloud-lightning', 'bi bi-cloud-lightning-fill'),
    @('bx bx-list-ol', 'bi bi-list-ol'),
    @('bx bx-list-ul', 'bi bi-list-ul'),
    @('bx bx-list-check', 'bi bi-list-check'),
    @('bx bx-list-plus', 'bi bi-plus-square-fill'),
    @('bx bx-detail', 'bi bi-card-list'),
    @('bx bx-label', 'bi bi-tag'),
    @('bx bx-tag-alt', 'bi bi-tags-fill'),
    @('bx bx-tag', 'bi bi-tag-fill'),
    @('bx bx-category-alt', 'bi bi-grid-fill'),
    @('bx bx-category', 'bi bi-grid'),
    @('bx bx-package', 'bi bi-box-seam-fill'),
    @('bx bx-box', 'bi bi-box-fill'),
    @('bx bx-basket', 'bi bi-basket-fill'),
    @('bx bx-store-alt', 'bi bi-shop-window'),
    @('bx bx-store', 'bi bi-shop'),
    @('bx bx-building', 'bi bi-building-fill'),
    @('bx bx-buildings', 'bi bi-buildings-fill'),
    @('bx bx-hotel', 'bi bi-building'),
    @('bx bx-task-x', 'bi bi-clipboard-x-fill'),
    @('bx bx-task', 'bi bi-clipboard-check-fill'),
    @('bx bx-clipboard', 'bi bi-clipboard-fill'),
    @('bx bx-support', 'bi bi-headset'),
    @('bx bx-comment-detail', 'bi bi-chat-square-text-fill'),
    @('bx bx-comment', 'bi bi-chat-square'),
    @('bx bx-conversation', 'bi bi-chat-right-text-fill'),
    @('bx bx-image-alt', 'bi bi-image-fill'),
    @('bx bx-image', 'bi bi-image'),
    @('bx bx-images', 'bi bi-images'),
    @('bx bx-photo-album', 'bi bi-collection-fill'),
    @('bx bx-collection', 'bi bi-collection'),
    @('bx bx-table', 'bi bi-table'),
    @('bx bx-grid-alt', 'bi bi-grid-1x2-fill'),
    @('bx bx-grid', 'bi bi-grid-fill'),
    @('bx bx-column', 'bi bi-layout-three-columns'),
    @('bx bx-layout', 'bi bi-layout-wtf'),
    @('bx bx-sidebar', 'bi bi-layout-sidebar'),
    @('bx bx-dock-left', 'bi bi-layout-sidebar'),
    @('bx bx-window-alt', 'bi bi-window'),
    @('bx bx-window', 'bi bi-window-stack'),
    @('bx bx-expand-alt', 'bi bi-fullscreen'),
    @('bx bx-expand', 'bi bi-arrows-fullscreen'),
    @('bx bx-collapse', 'bi bi-fullscreen-exit'),
    @('bx bx-fullscreen', 'bi bi-fullscreen'),
    @('bx bx-exit-fullscreen', 'bi bi-fullscreen-exit'),
    @('bx bx-move-vertical', 'bi bi-arrow-down-up'),
    @('bx bx-move-horizontal', 'bi bi-arrow-left-right'),
    @('bx bx-move', 'bi bi-arrows-move'),
    @('bx bx-target-lock', 'bi bi-bullseye'),
    @('bx bx-bullseye', 'bi bi-bullseye'),
    @('bx bx-crosshair', 'bi bi-crosshair'),
    @('bx bx-dots-vertical-rounded', 'bi bi-three-dots-vertical'),
    @('bx bx-dots-horizontal-rounded', 'bi bi-three-dots'),
    @('bx bx-dots-vertical', 'bi bi-three-dots-vertical'),
    @('bx bx-dots-horizontal', 'bi bi-three-dots'),
    @('bx bx-right-top-arrow-circle', 'bi bi-arrow-up-right-circle-fill'),
    @('bx bx-right-arrow-circle', 'bi bi-arrow-right-circle-fill'),
    @('bx bx-right-arrow-alt', 'bi bi-arrow-right'),
    @('bx bx-right-arrow', 'bi bi-caret-right-fill'),
    @('bx bx-left-arrow-circle', 'bi bi-arrow-left-circle-fill'),
    @('bx bx-left-arrow-alt', 'bi bi-arrow-left'),
    @('bx bx-left-arrow', 'bi bi-caret-left-fill'),
    @('bx bx-up-arrow-circle', 'bi bi-arrow-up-circle-fill'),
    @('bx bx-up-arrow-alt', 'bi bi-arrow-up'),
    @('bx bx-up-arrow', 'bi bi-caret-up-fill'),
    @('bx bx-down-arrow-circle', 'bi bi-arrow-down-circle-fill'),
    @('bx bx-down-arrow-alt', 'bi bi-arrow-down'),
    @('bx bx-down-arrow', 'bi bi-caret-down-fill'),
    @('bx bx-transfer-alt', 'bi bi-arrow-left-right'),
    @('bx bx-transfer', 'bi bi-shuffle'),
    @('bx bx-repeat', 'bi bi-repeat'),
    @('bx bx-repost', 'bi bi-arrow-repeat'),
    # Boxicons Solid (bxs-)
    @('bx bxs-user-check', 'bi bi-person-check-fill'),
    @('bx bxs-user-plus', 'bi bi-person-plus-fill'),
    @('bx bxs-user-x', 'bi bi-person-x-fill'),
    @('bx bxs-user-voice', 'bi bi-person-lines-fill'),
    @('bx bxs-user-circle', 'bi bi-person-circle'),
    @('bx bxs-user', 'bi bi-person-fill'),
    @('bx bxs-group', 'bi bi-people-fill'),
    @('bx bxs-trash-alt', 'bi bi-trash3'),
    @('bx bxs-trash', 'bi bi-trash3-fill'),
    @('bx bxs-edit-alt', 'bi bi-pencil-square'),
    @('bx bxs-edit', 'bi bi-pencil-fill'),
    @('bx bxs-show', 'bi bi-eye-fill'),
    @('bx bxs-hide', 'bi bi-eye-slash-fill'),
    @('bx bxs-plus-circle', 'bi bi-plus-circle-fill'),
    @('bx bxs-minus-circle', 'bi bi-dash-circle-fill'),
    @('bx bxs-check-circle', 'bi bi-check-circle-fill'),
    @('bx bxs-error-circle', 'bi bi-exclamation-circle-fill'),
    @('bx bxs-error', 'bi bi-exclamation-octagon-fill'),
    @('bx bxs-info-circle', 'bi bi-info-circle-fill'),
    @('bx bxs-help-circle', 'bi bi-question-circle-fill'),
    @('bx bxs-bell', 'bi bi-bell-fill'),
    @('bx bxs-cog', 'bi bi-gear-fill'),
    @('bx bxs-home', 'bi bi-house-fill'),
    @('bx bxs-map', 'bi bi-map-fill'),
    @('bx bxs-map-pin', 'bi bi-geo-alt-fill'),
    @('bx bxs-phone', 'bi bi-telephone-fill'),
    @('bx bxs-envelope', 'bi bi-envelope-fill'),
    @('bx bxs-message-detail', 'bi bi-chat-text-fill'),
    @('bx bxs-message', 'bi bi-chat-fill'),
    @('bx bxs-lock', 'bi bi-lock-fill'),
    @('bx bxs-lock-open', 'bi bi-unlock-fill'),
    @('bx bxs-key', 'bi bi-key-fill'),
    @('bx bxs-star', 'bi bi-star-fill'),
    @('bx bxs-bookmark', 'bi bi-bookmark-fill'),
    @('bx bxs-calendar', 'bi bi-calendar3'),
    @('bx bxs-time', 'bi bi-clock-fill'),
    @('bx bxs-money', 'bi bi-cash-stack'),
    @('bx bxs-purchase-tag', 'bi bi-tag-fill'),
    @('bx bxs-tag', 'bi bi-tag-fill'),
    @('bx bxs-receipt', 'bi bi-receipt'),
    @('bx bxs-file', 'bi bi-file-earmark-fill'),
    @('bx bxs-folder', 'bi bi-folder-fill'),
    @('bx bxs-cloud-download', 'bi bi-cloud-download-fill'),
    @('bx bxs-cloud-upload', 'bi bi-cloud-upload-fill'),
    @('bx bxs-data', 'bi bi-database-fill'),
    @('bx bxs-server', 'bi bi-server'),
    @('bx bxs-bar-chart-alt-2', 'bi bi-bar-chart-fill'),
    @('bx bxs-pie-chart', 'bi bi-pie-chart-fill'),
    @('bx bxs-report', 'bi bi-clipboard-data-fill'),
    @('bx bxs-badge-check', 'bi bi-patch-check-fill'),
    @('bx bxs-shield', 'bi bi-shield-fill'),
    @('bx bxs-wrench', 'bi bi-wrench-adjustable'),
    @('bx bxs-package', 'bi bi-box-seam-fill'),
    @('bx bxs-store', 'bi bi-shop'),
    @('bx bxs-building', 'bi bi-building-fill'),
    @('bx bxs-grid', 'bi bi-grid-fill'),
    @('bx bxs-dashboard', 'bi bi-speedometer2'),
    @('bx bxs-devices', 'bi bi-devices'),
    @('bx bxs-chip', 'bi bi-cpu-fill'),
    @('bx bxs-mobile', 'bi bi-phone-fill'),
    @('bx bxs-laptop', 'bi bi-laptop'),
    @('bx bxs-network-chart', 'bi bi-diagram-3-fill'),
    @('bx bxs-printer', 'bi bi-printer-fill'),
    @('bx bxs-credit-card', 'bi bi-credit-card-fill'),
    @('bx bxs-layer', 'bi bi-layers-fill'),
    @('bx bxs-spreadsheet', 'bi bi-file-earmark-spreadsheet-fill'),
    @('bx bxs-task', 'bi bi-clipboard-check-fill'),
    @('bx bxs-conversation', 'bi bi-chat-right-text-fill'),
    @('bx bxs-chart', 'bi bi-graph-up'),
    @('bx bxs-label', 'bi bi-tags-fill'),
    # Boxicons Logos (bxl-) 
    @('bx bxl-whatsapp-square', 'bi bi-whatsapp'),
    @('bx bxl-whatsapp', 'bi bi-whatsapp'),
    @('bx bxl-telegram', 'bi bi-telegram'),
    @('bx bxl-facebook', 'bi bi-facebook'),
    @('bx bxl-twitter', 'bi bi-twitter-x'),
    @('bx bxl-instagram', 'bi bi-instagram'),
    @('bx bxl-youtube', 'bi bi-youtube'),
    @('bx bxl-github', 'bi bi-github'),
    @('bx bxl-google', 'bi bi-google'),
    @('bx bxl-linkedin', 'bi bi-linkedin'),
    # Fallback untuk bx icons yang tidak dikenal
    @('bx bxs-[a-z0-9\-]+', 'bi bi-dot'),
    @('bx bxl-[a-z0-9\-]+', 'bi bi-box'),
    @('bx bx-[a-z0-9\-]+', 'bi bi-circle')
)

# =============================================================================
# Jalankan replacement
# =============================================================================
$totalFiles = 0
$totalReplacements = 0

foreach ($file in $ejsFiles) {
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    $originalContent = $content
    $fileReplacements = 0

    foreach ($mapping in $iconMappings) {
        $pattern = $mapping[0]
        $replacement = $mapping[1]
        $newContent = [regex]::Replace($content, $pattern, $replacement)
        if ($newContent -ne $content) {
            $count = ([regex]::Matches($content, $pattern)).Count
            $fileReplacements += $count
            $content = $newContent
        }
    }

    if ($content -ne $originalContent) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8 -NoNewline
        $totalFiles++
        $totalReplacements += $fileReplacements
        Write-Host "  [FIXED] $($file.Name) - $fileReplacements replacements" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "=== Selesai ===" -ForegroundColor Cyan
Write-Host "Files diubah  : $totalFiles" -ForegroundColor Green
Write-Host "Total icon fix: $totalReplacements" -ForegroundColor Green
